module.exports = {
  extends: ['gitmoji'],
  parserPreset: '@gitmoji/parser-opts',
  rules: {
    'body-leading-blank': [1, 'always'],
    //not setting any max-line-length since we are writing release-notes
    //in our chore(release) commit messages. @see release.config.ts '@semantic-release/git' configurations.
    //'body-max-line-length': [2, 'always', 100] as const,
    'footer-leading-blank': [1, 'always'],
    // 'footer-max-line-length': [
    //     2,
    //     'always',
    //     100,
    // ] as const,
    'header-max-length': [2, 'always', 100],
    'header-trim': [2, 'always'],
    'subject-case': [
      2,
      'never',
      ['sentence-case', 'start-case', 'pascal-case', 'upper-case'],
    ],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'style',
        'perf',
        'prune',
        'fix',
        'quickfix',
        'feature',
        'docs',
        'deploy',
        'ui',
        'init',
        'test',
        'security',
        'release',
        'lint',
        'wip',
        'fix-ci',
        'downgrade',
        'upgrade',
        'pushpin',
        'ci',
        'analytics',
        'refactoring',
        'dep-add',
        'dep-rm',
        'config',
        'i18n',
        'typo',
        'poo',
        'revert',
        'merge',
        'dep-up',
        'compat',
        'mv',
        'license',
        'breaking',
        'assets',
        'access',
        'docs-code',
        'beer',
        'texts',
        'db',
        'log-add',
        'log-rm',
        'contrib-add',
        'ux',
        'arch',
        'iphone',
        'clown-face',
        'egg',
        'see-no-evil',
        'camera-flash',
        'experiment',
        'seo',
        'types',
        'seed',
        'flags',
        'animation',
        'wastebasket',
        'passport-control',
        'adhesive-bandage',
        'monocle-face',
        'coffin',
        'test-tube',
        'necktie',
        'stethoscope',
        'bricks',
        'technologist',
        'chore',
      ],
    ],
  },
};
